apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgrespv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/postgres-vol"