apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
spec:
  replicas: 4
  selector:
   matchLabels:
    app: nginx
    tier: frontend
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        tier: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - name: http
              protocol: TCP
              containerPort: 80
          env:
           - name: NGINX_HOME
             value: "/etc/nginx"
          volumeMount:
            - name: nginx-vol1
              mountPath: "/etc/nginx/html"
      volumes:
        - name: nginx-vol1
          hostPath:
            path: "/mnt/nginx-vol1"