apiVersion: v1
kind: ReplicationController
metadata:
  name: httpd
spec:
  replicas: 4
  selector:
    app: httpd
    tier: frontend
  template:
    metadata:
      name: httpd
      labels:
        app: httpd
        tier: frontend
    spec:
      containers:
        - name: httpd
          image: httpd:latest
          ports:
            - name: http
              protocol: TCP
              containerPort: 80
          env:
            - name: APACHE_HOME
              value: "/usr/local/apach2"